version: '3.8'

services:
  debian:
    build: .
    volumes:
      - .:/workspace
    entrypoint: ["tail", "-f", "/dev/null"]
    command: "/bin/bash"
    # entrypoint: ["/bin/bash", "./install.sh"]
    stdin_open: true # docker run -i
    tty: true
